Li home work
Kolesa-Education/kolesa-upgrade-homework-8 pull request #5
Opened 2022-10-20 21:06 UTC by Koala610

2022-10-21 05:00 UTC, Koala610 commented
Здравствуйте. Программа может не запуститься или скомпилироваться с ошибкой. Если такая проблема возникнет откатитесь на данный коммит [83728a1](https://github.com/Kolesa-Education/kolesa-upgrade-homework-8/pull/5/commits/83728a10e731c8d77b365c1bb73199dcf152e8bf)

2022-10-25 11:59 UTC, Tazya requested changes
Не работает конкурентность. В остальном в плане расчёта комбинаций всё отлично. Самая ресурсоёмкая операция выделена и нужно немного изменить, чтобы работало конкурентно.

Попробуй переделать на waitGroup

2022-10-25 11:59 UTC, Tazya commented on main.go
> +			go findCombination(cardCombinations[i], channel)
Тут нет конкурентности. Получается так, что канал блокирует выполнение до получения значения из канала.
И он используется тут только для того, чтобы передать данные.

2022-10-25 11:59 UTC, Tazya commented on main.go
> +			go findCombination(cardCombinations[i], channel)
В итоге программа работает даже медленнее, т.к. появились расходы, связанные с блокировкой исполнения.
Результаты на моей системе 
1. С каналами и горутинами
```
2022/10/25 17:53:56 Finished in {523690485}ns/{523}ms
```

2. Без каналов и горутин 
```2022/10/25 17:50:52 Finished in {221372127}ns/{221}ms``

2022-10-25 18:32 UTC, Koala610 commented on main.go
> +func getCombinationsPerFile(file os.FileInfo) []string {
Вынес поиск комбинаций в файле в одну функцию

2022-10-26 04:54 UTC, Tazya approved these changes

2022-10-26 04:54 UTC, closed without merging